server:
  port: 9100

spring:
  application:
    name: app-eureka-center

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9200/eureka/     #register to another eureka server
    #register itself to Eureka server,if itself is register center, false，but in cluster true
    register-with-eureka: true
    fetch-registry: true

  #in dev, test env can set it to false to make sure exclude it when the service is down
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000