server:
  port: 8200

spring:
  application:
    name: order-api

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9100/eureka/,http://127.0.0.1:9200/eureka/
    register-with-eureka: true
    fetch-registry: true

feign:
  hystrix:
    enabled: true

swagger:
  base-package: com.kevin.orderapi