# 基于java镜像创建新镜像
FROM openjdk:8-jdk-alpine
MAINTAINER Kevin Xiong
# 将jar包添加到容器中并更名为eureka-server-a.jar
ADD target/*.jar /usr/src/app/eureka-server-a.jar
# 运行jar包
ENTRYPOINT ["java","-jar","/usr/src/app/eureka-server-a.jar"]

# build: docker build -t eureka-server-a .
# run: docker run --name eureka-server-a -p 9100:9100 eureka-server-a