spring:
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:config/,classpath:config/cloud

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:9100/eureka/