server:
  port: 8100

spring:
  application:
    name: product-api

#register to eureka server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9100/eureka/,http://127.0.0.1:9200/eureka/
    #as this is eureka client,so need to register to server
    register-with-eureka: true
    fetch-registry: true